# docker-compose.yml
version: "3.8"

services:
  # ----------------------------------------
  # 1. SERVIÇO DO BANCO DE DADOS (PostgreSQL)
  # ----------------------------------------
  db:
    image: postgres:16-alpine
    container_name: catalogo_db
    environment:
      POSTGRES_DB: catalogo_pedidos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./data-volumes/postgres/data:/var/lib/postgresql/data
    # restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d catalogo_pedidos"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ----------------------------------------
  # 2. SERVIÇO DO BACKEND (.NET 8 Web API)
  # ----------------------------------------
  backend:
    container_name: catalogo_backend
    build:
      context: ./backend # Caminho para o Dockerfile do backend
      dockerfile: Dockerfile
      args:
        - CONFIGURATION=Release # Build otimizado
    restart: always
    ports:
      - "5000:8080" # Mapeia a porta do contêiner para a porta local
    environment:
      # Connection String que o .NET 8 usará (referencia o serviço 'db')
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${DB_NAME:-catalogo_pedidos};Username=${DB_USER:-postgres};Password=${DB_PASSWORD:-postgres123}"
      ASPNETCORE_URLS: "http://+:8080"
    depends_on:
      db:
        condition: service_healthy # Garante que o banco esteja pronto antes de subir
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # ----------------------------------------
  # 3. SERVIÇO DO FRONTEND (Angular 17+)
  # ----------------------------------------
  frontend:
    container_name: catalogo_frontend
    build:
      context: ./frontend # Caminho para o Dockerfile do frontend
      dockerfile: Dockerfile
    # restart: always
    ports:
      - "4200:80" # Nginx servindo Angular na porta 80 do contêiner
    # depends_on:
    #   backend:
    #     condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
